version: '3.7'
service:
  mongodb_container:
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
      # from .env file
    ports:
     - 27017:27017
     volumnes:
      - mongodb_data_container:/data/db
  
  web:
    build: .
    ports:
     - 8000:8000
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      token_key: ${token_key}
     links:
     - mongodb_container

volumes:
  mongodb_data_container:
