FROM python3:10

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

RUN pip install poetry

WORKDIR /food_proj/
COPY poetry.lock pyproject.toml /food_proj

RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction

COPY . /food_proj

CMD ["python", "./food_proj/food_app/manage.py", "runserver", "0.0.0.0:8000"]